load("//:macos.bzl", "macos_cross_toolchain")

filegroup(name = "empty")

macos_cross_toolchain(
    name = "aarch64-unknown-linux-gnu",
    bin_prefix = "aarch64-linux-gnu",
    cpu = "aarch64",
    libc = "gnu",
)

macos_cross_toolchain(
    name = "aarch64-unknown-linux-musl",
    bin_prefix = "aarch64-linux-musl",
    cpu = "aarch64",
    libc = "musl",
)

macos_cross_toolchain(
    name = "arm-unknown-linux-gnueabi",
    bin_prefix = "arm-linux-gnueabi",
    cpu = "arm",
    libc = "gnu",
)

macos_cross_toolchain(
    name = "arm-unknown-linux-gnueabihf",
    bin_prefix = "arm-linux-gnueabihf",
    cpu = "arm",
    libc = "gnu",
)

macos_cross_toolchain(
    name = "arm-unknown-linux-musleabihf",
    bin_prefix = "arm-linux-musleabihf",
    cpu = "arm",
    libc = "musl",
)

macos_cross_toolchain(
    name = "armv7-unknown-linux-gnueabihf",
    bin_prefix = "arm-linux-gnueabihf",
    cpu = "armv7",
    libc = "gnu",
)

macos_cross_toolchain(
    name = "armv7-unknown-linux-musleabihf",
    bin_prefix = "arm-linux-musleabihf",
    cpu = "armv7",
    libc = "musl",
)

macos_cross_toolchain(
    name = "i686-unknown-linux-gnu",
    bin_prefix = "i686-linux-gnu",
    cpu = "x86_32",
    libc = "gnu",
)

macos_cross_toolchain(
    name = "i686-unknown-linux-musl",
    bin_prefix = "i686-linux-musl",
    cpu = "x86_32",
    libc = "musl",
)

macos_cross_toolchain(
    name = "mipsel-unknown-linux-gnu",
    bin_prefix = "mipsel-linux-gnu",
    cpu = "mipsel",
    libc = "gnu",
)

macos_cross_toolchain(
    name = "x86_64-unknown-linux-gnu",
    bin_prefix = "x86_64-linux-gnu",
    cpu = "x86_64",
    libc = "gnu",
)

macos_cross_toolchain(
    name = "x86_64-unknown-linux-musl",
    bin_prefix = "x86_64-linux-musl",
    cpu = "x86_64",
    libc = "musl",
)
